[[items]]
filename = "sword.png"
name = "Sword"
description = "Sadly less mighty than the pen."
chance_percent = 10

[[items]]
filename = "mysterious-potion.png"
name = "Mysterious Potion"
description = "Warning: Choking Hazard"
chance_percent = 15

[[items]]
filename = "game-controller.png"
name = "Game Controller"
description = "Are ya winning son?"
chance_percent = 10

[[items]]
filename = "almond-water.png"
name = "Almond Water"
description = "Keep your sanity."
chance_percent = 23.9

[[items]]
filename = "bone.png"
name = "Bone"
description = "Isn’t that concerning?"
chance_percent = 5

[[items]]
filename = "umbrella.png"
name = "Umbrella"
description = "An umbrella, not an umbrella cookie.."
chance_percent = 5

[[items]]
filename = "rotary-phone.png"
name = "Rotary Phone"
description = "I feel old."
chance_percent = 5

[[items]]
filename = "science-fair-volcano.png"
name = "Science Fair Volcano"
description = "Thought that was real for a second!"
chance_percent = 4

[[items]]
filename = "broken-file.png"
name = "Broken File"
description = "You just had to break the game, did you?"
chance_percent = 3

[[items]]
filename = "potted-cactus.png"
name = "Potted Cactus"
description = "Please don’t sit on this."
chance_percent = 3

[[items]]
filename = "mind.png"
name = "Mind"
description = "Our devs lost these a while ago, return immediately."
chance_percent = 2

[[items]]
filename = "candy-cane.png"
name = "Candy Cane"
description = "Don’t eat that, it’s from the Christmas event two years ago!."
chance_percent = 2

[[items]]
filename = "lootbox.gif"
name = "Lootbox"
description = "A lootbox in a lootbox?"
chance_percent = 2

[[items]]
filename = "delivery-box.png"
name = "Delivery Box"
description = "Now how did this get here?"
chance_percent = 2

[[items]]
filename = "lemon.png"
name = "Lemon"
description = "Something normal for onc- AH GET IT OUT OF HERE!!!"
chance_percent = 3

[[items]]
filename = "grass.png"
name = "Grass"
description = "Do not touch, for display only."
chance_percent = 1

[[items]]
filename = "cement-pillow.png"
name = "Cement Pillow"
description = "Why does this even exist?"
chance_percent = 1

[[items]]
filename = "hexapad.gif"
name = "Hexapad"
description = "We shape our tools, and then our tools shape us."
chance_percent = 0.4

[[items]]
filename = "infinitediamond’s-key.gif"
name = "InfiniteDiamond’s Key"
description = "It’s the key! DM InfiniteDiamond with a screenshot of the page for a reward."
chance_percent = 0.6

[[items]]
filename = "schrodingers-cat.gif"
name = "Schrodinger’s Cat"
description = "The cat escaped, and it wants revenge."
chance_percent = 0.9

[[items]]
filename = "grilled-cheese-sandwich.gif"
name = "Grilled Cheese Sandwich"
description = "That sandwich was DELICIOUS!! What did you put in it?"
chance_percent = 0.1

[[items]]
filename = "loot-table.png"
name = "Loot Table"
description = "For my eyes only:https://is.gd/ekiruy"
chance_percent = 0.1
