[[items]]
filename = "sword.png"
name = "Sword"
description = "Sadly less mighty than the pen."
chance_percent = 35

[[items]]
filename = "mysterious-potion.png"
name = "Mysterious Potion"
description = "Warning: Choking Hazard"
chance_percent = 25

[[items]]
filename = "game-controller.png"
name = "Game Controller"
description = "Are ya winning son?"
chance_percent = 1000

[[items]]
filename = "bone.png"
name = "Bone"
description = "Isn’t that concerning?"
chance_percent = 7

[[items]]
filename = "cement-pillow.png"
name = "Cement Pillow"
description = "Great for fights!"
chance_percent = 5

[[items]]
filename = "potted-cactus.png"
name = "Potted Cactus"
description = "Please don’t sit on this."
chance_percent = 5

[[items]]
filename = "rotary-phone.png"
name = "Rotary Phone"
description = "I feel old."
chance_percent = 5


[[items]]
filename = "candy-cane.png"
name = "Candy Cane"
description = "Don’t eat that, it’s from the Christmas event two years ago!"
chance_percent = 2.5

[[items]]
filename = "bubblegum.png"
name = "Bubble Gum"
description = "I came here to open lootboxes and chew bubblegum, and I’m all out of bubblegum!"
chance_percent = 4

[[items]]
filename = "fjsdfdjkfdjklfdsjflkdfjdklfjfjdlsk.png" # broken file
name = "Broken File"
description = "You just had to break the game, did you?"
chance_percent = 3


[[items]]
filename = "grass.png"
name = "Grass"
description = "Do not touch, for display only."
chance_percent = 2.5

[[items]]
filename = "lootbox.png"
name = "Lootbox"
description = "A lootbox in a lootbox?"
chance_percent = 2.5

[[items]]
filename = "delivery-box.png"
name = "Delivery Box"
description = "Now how did this get here?"
chance_percent = 2.5

[[items]]
filename = "cosmic-berries.gif"
name = "Cosmic Berries"
description = "Imported straight from the vineyards of Neptune."
chance_percent = 0.8

[[items]]
filename = "infinitediamonds-key.gif"
name = "Infinite Diamond's Key"
description = "It’s the key! DM InfiniteDiamond with a screenshot of the page for a reward."
chance_percent = 0.2
